### ISSUE TITLE
please check "Input" section of the description 

### ISSUE THREAD

**Issue by sirpete83** [hotNipi/node-red-contrib-ui-statechart#6]
Hallo,
please check the Input section:#

msg.payload = [{series:"A",value:123,state:true, color:"#00CC45"},{series:"D",value:32,state:false}]

but it should be:

msg.payload = [{"series":"A","value":123,"state":true, "color":"#00CC45"},{"series":"D","value":32,"state":false}]

best regards Peter

**Comment by hotNipi** [comment]
Not really. 
JavaScript object's property name doesn't have to be string. And in this format the syntax is correct. You can use it directly inside function node. 
If you use inject node, you can not create or send JavaScript Object but JSON and for sure in that case you are forced to use strings for keys (property names) because of that's required by JSON.

**Comment by sirpete83** [comment]
Thanks for the clarification. Right, I had used the Inject node. I'm new to this topic. I would have been surprised that no one else had noticed.
Maybe you could mention the info about the inject node for the newbies.

**Comment by hotNipi** [comment]
Well, the common practice is that node should do and deal only with its own business. Meaning that if node declares that it will add two numbers together and outputs the result, it should never offer any other operation. And that should be reflected in node's docs. 
So I think that such kind of educational stuff should stay in the Node-RED documentation [https://nodered.org/docs/user-guide/](url) page where it is organized and maintained by owners/creators.

**Comment by sirpete83** [comment]
But one think is not clear to me. If I provide :
[{series:"A",value:123,state:true, color:"#00CC45"},{series:"D",value:32,state:false}]
as a string, of the payload by the inject node, I get the error se
ries undefined.

![inject_node](https://user-images.githubusercontent.com/7904787/218669192-5dc12aec-857f-4a53-a4f8-ef5c1b957355.PNG)

**Comment by hotNipi** [comment]
If you inject it as string, it will be string. Statechart can't do anything with string. It requires input to be as explained here [https://github.com/hotNipi/node-red-contrib-ui-statechart#input](url)

**Comment by sirpete83** [comment]
Ok, got it. It is confusing but now clear. Test with a Function node and setting the payload to [{series:"0",value:12.3,state:true}] works fine. 
Not clear for me why it should not process strings and raw data, but I think there is a reason for that.

**Comment by hotNipi** [comment]
To make the world connected it takes to have at least some kind of protocol. If native English speaker comes to Estonia he/she finds that people do communicate in strange language. Can any of such talking taken as useful input? Definitely not. So they try to agree which language both can understand and switch to it. Protocol agreed and if followed the communication works. Simple as that.

**Comment by sirpete83** [comment]
I agree, but the "language" ([{series:"0",value:12.3,state:true}]) your case is the same. only the way to transfere is another. I can speak [{series:"0",value:12.3,state:true}] the protocol or sing "[{series:"0",value:12.3,state:true}]" the protocol, and my receiver would understand me.

**Comment by hotNipi** [comment]
Maybe yeah, not best example I provided but in JavaScript the string, object and JSON are different things. Even if they look very similar. 

JSON is actually string. But not every string can be JSON.

 String "[{series:"0",value:12.3,state:true}]" is not valid JSON because it takes to have strings in property names. 

 Mostly in Node-RED the data formatting/converting is done by dedicated nodes and rarely you should think about how it is done or how it looks, but in case of testing and in the early phase of development you do use test data and then you do it by hand. And in those cases you'll have to follow the rules and that's learning curve you just need to follow.
